= local-kubernetes

Create local Kubernetes cluster easily.

== Supported Operating System

* Microsoft Windows 10 and 11

== Prerequisites

* Oracle VirtualBox
* Hashicorp Vagrant
* OpenSSH Client

== Virtual Machines

[cols=3*^,options=header]
|===
||Master|Worker

<|Node count
|1
|1

<|vCPU
|2
|2

<|Memory
|2 GB
|2 GB

<|Disk
2+|100 GB +

<|Operating System
2+|Debian 12 +
(Vagrant box debian/bookworm64)

<|IP Address
|192.168.8.10 /24|192.168.8.11 /24
|===

== Steps

. Clone or download-then-extract this repository.
. Open Terminal (Command Prompt or PowerShell)
. Change directory to local-kubernetes
. Confirm configuration in Vagrantfile
. Start up the cluster

[source,powershell]
----
vagrant up
----

[start=6]
. Wait until the above command completed. If UAC prompt appear for Virtualbox, please click "Yes"
. SSH to master node

[source,powershell]
----
vagrant ssh master
----

[start=8]
. Check all Kubernetes nodes

[source,bash]
----
sudo kubectl get nodes -o wide
----

== Customize

. Change Kubernetes version

Update the value of the KUBERNETES_VERSION in Vagrantfile

[source,ruby]
----
KUBERNETES_VERSION = "v1.30.0"
----

You can get list of valid versions using the following command

[source,powershell]
----
(Invoke-RestMethod -Uri "https://api.github.com/repos/kubernetes/kubernetes/releases?per_page=100" -UseBasicParsing).tag_name -notmatch "alpha|beta|rc"
----

[start=2]
. Create multiple worker nodes

Add or modify the IP_ADDRESSES array, separated by comma. The following example with create 1 master node with 3 worker nodes. First IP address is for master node and the second IP address and below are for worker nodes.

[source,ruby]
----
IP_ADDRESSES = [
  "192.168.8.10", 
  "192.168.8.11",
  "192.168.8.12",
  "192.168.8.13"
]
----

== Processes

. Vagrant will download the base image of configured operating system.
. Vagrant will create new VirtualBox virtual machine using the base image. It will perform few prerequisite task then assign the following info for each virtual machine.
** Hostname
** IP Address
. When the virtual machine ready, Vagrant will execute shell scripts to complete the cluster setup.
** Master node
... Install containerd, kubelet, kubeadm, kubectl.
... Initialize Kubernetes cluster
... Setup Calico pod networking
** Worker node
... Install containerd, kubelet, kubeadm, kubectl.
... Join Kubernetes cluster
. All above steps will be done 1 virtual machine at a time, starting with master node, then worker node.
