= image:https://skills-icons.vercel.app/api/icons?i=kubernetes[,30,30] local-kubernetes 
:toc:

== &#x1F3AF; Goal

Create local Kubernetes cluster easily.

&#x26A0; Currently support single cluster only.



== &#x2699; Supported Operating System

* Microsoft Windows 10 image:https://skills-icons.vercel.app/api/icons?i=windows[,20,20]
* Microsoft Windows 11 image:https://skills-icons.vercel.app/api/icons?i=windows[,20,20]

== &#x2705; Prerequisites

* At least quad core CPU
* At least 6 GB RAM free
* At least 32 GB SSD free space

* Oracle VirtualBox image:https://skills-icons.vercel.app/api/icons?i=virtualbox[,30,30]
* Hashicorp Vagrant

== &#x1F4BB; Virtual Machines

[cols=3*^,options=header]
|===
||Master &#x1F947; |Worker &#x1F948;

<|Node count
|1
|2

<|vCPU
|2
|2

<|Memory
|2 GB
|2 GB

<|Disk
|16 GB
|8 GB

<|Operating System
2+|Debian 12 image:https://skills-icons.vercel.app/api/icons?i=debian[,20,20] +
(Vagrant box debian/bookworm64)

<|IP Addresses
|192.168.8.10 /24|192.168.8.11 /24 +
192.168.8.12 /24
|===

== &#x1F680; Kickstart

. Clone or download-then-extract this repository.
. Open Terminal (Command Prompt or PowerShell)
. Change directory to local-kubernetes
. Confirm configuration in Vagrantfile
. Start up the cluster

[source,powershell]
----
vagrant up
----

[start=6]
. Wait until the above command completed. If UAC prompt appear for Virtualbox, please click "Yes"
. SSH to master node

[source,powershell]
----
vagrant ssh master
----

[start=8]
. Check all Kubernetes nodes

[source,bash]
----
kubectl get nodes -o wide
----

== &#x1F6E0; Customize

. Change Kubernetes version

Update the value of the KUBERNETES_VERSION in Vagrantfile

[source,ruby]
----
KUBERNETES_VERSION = "v1.30.0"
----

You can get list of valid versions using the following command

[source,powershell]
----
(Invoke-RestMethod -Uri "https://api.github.com/repos/kubernetes/kubernetes/releases?per_page=100" -UseBasicParsing).tag_name -notmatch "alpha|beta|rc"
----

[start=2]
. Different number of worker nodes

Update WORKER_NODES value to the desired number of worker nodes. Minimum 1, maximum up to the computer available resource.

[source,ruby]
----
WORKER_NODES = 1   # single worker node only
WORKER_NODES = 4   # 4 worker nodes
----

[start=3]
. Different master and worker names

Update `MASTER_NAME` and `WORKER_PREFIX` values.

[source,ruby]
----
# example: to match with killercoda
MASTER_NAME   = "controlplane"
WORKER_PREFIX = "node"   
----

[start=4]
. Different number of digits of worker nodes name postfix.

Update `WORKER_NUMBER_LENGTH` values.

[source,ruby]
----
WORKER_NUMBER_LENGTH = 4   # 4 digits with leading zeroes
----

== &#x23E9; How it works

. Vagrant will download the base image of configured operating system.
. Vagrant will create new VirtualBox virtual machine using the base image. It will perform few prerequisite task then assign the following info for each virtual machine.
** Hostname
** IP Address
. When the virtual machine ready, Vagrant will execute shell scripts to complete the cluster setup.
** Master node
... Install containerd, kubelet, kubeadm, kubectl, etcdctl, helm.
... Initialize Kubernetes cluster.
... Setup Calico pod networking with CIDR 10.10.0.0/16.
... Setup Rancher local-path storage provisioner and class.
... Create /etc/hosts entries.
... Create SSH keys and config.
** Worker nodes
... Install containerd, kubelet, kubeadm.
... Join Kubernetes cluster.
... Create /etc/hosts entries.
... Create SSH config and copy keys from master.
. All above steps will be done 1 virtual machine at a time, starting with master node, then worker node.


== &#x1FA7A; Troubleshooting

. If `vagrant ssh <node>` gives error `Permission denied`, please uncomment line with `c.ssh.insert_key` in `Vagrantfile`

. If IP addresses already in use, please change the `START_IP_ADDRESS` line with valid /24 IP address